In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('medical_cost_prediction_dataset.csv')

In [3]:
df.head()

,age,gender,bmi,smoker,diabetes,hypertension,heart_disease,asthma,physical_activity_level,daily_steps,sleep_hours,stress_level,doctor_visits_per_year,hospital_admissions,medication_count,insurance_type,insurance_coverage_pct,city_type,previous_year_cost,annual_medical_cost
0,69,Male,29.4,No,1,0,0,0,Medium,14825,4.4,8,1,0,4,Private,80,Semi-Urban,10885,2645.50
1,32,Female,22.9,No,1,0,0,0,Medium,3620,6.0,7,4,3,0,Government,64,Semi-Urban,18722,10959.70
2,89,Male,25.7,No,0,0,0,0,High,10578,4.5,7,2,0,3,NaN,0,Urban,4196,8409.80
3,78,Male,31.9,Yes,0,1,0,0,Low,6226,8.6,9,6,1,7,Government,70,Urban,11128,7996.62
4,38,Male,27.7,No,0,0,0,0,High,6253,5.7,3,6,0,6,Private,77,Urban,15110,3202.52

In [4]:
df.isnull().sum()

age                           0
gender                        0
bmi                           0
smoker                        0
diabetes                      0
hypertension                  0
heart_disease                 0
asthma                        0
physical_activity_level       0
daily_steps                   0
sleep_hours                   0
stress_level                  0
doctor_visits_per_year        0
hospital_admissions           0
medication_count              0
insurance_type             1048
insurance_coverage_pct        0
city_type                     0
previous_year_cost            0
annual_medical_cost           0
dtype: int64

In [5]:
df.shape

(5000, 20)

In [7]:
df.columns

Index(['age', 'gender', 'bmi', 'smoker', 'diabetes', 'hypertension',
       'heart_disease', 'asthma', 'physical_activity_level', 'daily_steps',
       'sleep_hours', 'stress_level', 'doctor_visits_per_year',
       'hospital_admissions', 'medication_count', 'insurance_type',
       'insurance_coverage_pct', 'city_type', 'previous_year_cost',
       'annual_medical_cost'],
      dtype='object')

In [9]:
df['insurance_type'] = df['insurance_type'].fillna('No Insurance')

In [11]:
df['insurance_type'].unique()

array(['Private', 'Government', 'No Insurance'], dtype=object)

In [12]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['gender'] = encoder.fit_transform(df['gender'])
df['smoker'] = encoder.fit_transform(df['smoker'])
df['insurance_type'] = encoder.fit_transform(df['insurance_type'])

In [14]:
df.head()

,age,gender,bmi,smoker,diabetes,hypertension,heart_disease,asthma,physical_activity_level,daily_steps,sleep_hours,stress_level,doctor_visits_per_year,hospital_admissions,medication_count,insurance_type,insurance_coverage_pct,city_type,previous_year_cost,annual_medical_cost
0,69,1,29.4,0,1,0,0,0,Medium,14825,4.4,8,1,0,4,2,80,Semi-Urban,10885,2645.50
1,32,0,22.9,0,1,0,0,0,Medium,3620,6.0,7,4,3,0,0,64,Semi-Urban,18722,10959.70
2,89,1,25.7,0,0,0,0,0,High,10578,4.5,7,2,0,3,1,0,Urban,4196,8409.80
3,78,1,31.9,1,0,1,0,0,Low,6226,8.6,9,6,1,7,0,70,Urban,11128,7996.62
4,38,1,27.7,0,0,0,0,0,High,6253,5.7,3,6,0,6,2,77,Urban,15110,3202.52

In [15]:
from sklearn.model_selection import train_test_split
X = df[['age','gender','bmi',	'smoker',	'diabetes',	'hypertension',	'heart_disease',	'asthma'	]]
y = df['annual_medical_cost']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [17]:
X.columns

Index(['age', 'gender', 'bmi', 'smoker', 'diabetes', 'hypertension',
       'heart_disease', 'asthma'],
      dtype='object')

In [18]:
y.shape

(5000,)

In [19]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test,y_pred)
print("mae :",mae)

mae : 5646.785510650715

In [20]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print("R2 Score:", r2)

R2 Score: -0.1810068690465485

In [21]:
X = df[['age','gender','bmi','smoker','diabetes',
        'hypertension','heart_disease','asthma']]
y = df['annual_medical_cost']

In [22]:
X = pd.get_dummies(
    X,
    columns=['gender','smoker','diabetes',
             'hypertension','heart_disease','asthma'],
    drop_first=True
)

In [23]:
y_log = np.log1p(y)

In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y_log, test_size=0.2, random_state=42
)

In [25]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=300,
    max_depth=15,
    min_samples_split=5,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

RandomForestRegressor(max_depth=15, min_samples_split=5, n_estimators=300,
                      n_jobs=-1, random_state=42)

In [26]:
from sklearn.metrics import mean_absolute_error, r2_score

y_pred_log = model.predict(X_test)

y_pred = np.expm1(y_pred_log)
y_true = np.expm1(y_test)

mae = mean_absolute_error(y_true, y_pred)
r2 = r2_score(y_true, y_pred)

print("MAE:", mae)
print("R2 Score:", r2)

MAE: 4964.72027683718
R2 Score: -0.10773125210786816

In [27]:
df.columns

Index(['age', 'gender', 'bmi', 'smoker', 'diabetes', 'hypertension',
       'heart_disease', 'asthma', 'physical_activity_level', 'daily_steps',
       'sleep_hours', 'stress_level', 'doctor_visits_per_year',
       'hospital_admissions', 'medication_count', 'insurance_type',
       'insurance_coverage_pct', 'city_type', 'previous_year_cost',
       'annual_medical_cost'],
      dtype='object')

In [28]:
X = df.drop('annual_medical_cost', axis=1)
y = df['annual_medical_cost']

In [29]:
# Numerical columns and then fill with median
num_cols = X.select_dtypes(include=['int64','float64']).columns
X[num_cols] = X[num_cols].fillna(X[num_cols].median())

# Categorical columns then fill with 'Unknown'
cat_cols = X.select_dtypes(include=['object']).columns
X[cat_cols] = X[cat_cols].fillna('Unknown')

In [30]:
X = pd.get_dummies(X, drop_first=True)

In [31]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [32]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=500,
    max_depth=20,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

RandomForestRegressor(max_depth=20, min_samples_leaf=2, min_samples_split=5,
                      n_estimators=500, n_jobs=-1, random_state=42)

In [33]:
from sklearn.metrics import mean_absolute_error, r2_score

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("R2 Score:", r2)

MAE: 633.1220797720689
R2 Score: 0.9789732374541873